export enum REPOSITORY_INFO_TYPE_KEYS {
  SET_CURRENT_REPOSITORY = "GA/repositoryInfo/SET_CURRENT_REPOSITORY",
  GET_PULL_REQUEST_INFO = "GA/repositoryInfo/GET_PULL_REQUEST_INFO",
  GET_ISSUE_INFO = "GA/repositoryInfo/GET_ISSUE_INFO",
  GET_COMMIT_INFO = "GA/repositoryInfo/GET_COMMIT_INFO"
}
